# Generated by Django 6.1.1 on 2026-10-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=50)),
                ('user_role', models.CharField(default='anonymous', max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('utid', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('NON_REPLIER', 'Non-replier sample'), ('CLAIMED_JOB', 'Claimed job sample')], max_length=20)),
                ('probability', models.FloatField(help_text='Probability p of being sampled; weight = 1 / p')),
                ('result_verified', models.BooleanField(blank=True, null=True)),
                ('called_by', models.CharField(blank=True, max_length=50, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'audit_sample',
            },
        ),
        migrations.CreateModel(
            name='CertificateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=60)),
                ('verification_status', models.CharField(default='VERIFIED', help_text='VERIFIED | NOT_FOUND | CONSENT_MISSING', max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'certificate_check',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('follow-up', 'Follow-up contact'), ('employer_check', 'Employer validation'), ('record_match', 'Record match'), ('statistics', 'Statistics')], max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=20)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('notice_version', models.CharField(default='1.0', help_text='Version of the notice the trainee saw', max_length=20)),
                ('given_by', models.CharField(default='trainee', help_text='trainee or guardian', max_length=50)),
            ],
            options={
                'db_table': 'consent',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('utid', models.CharField(help_text='Unique Trainee ID, format KO-YYYYMMDD-NNNN (F-03)', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('X', 'Unspecified')], default='X', max_length=1)),
                ('category', models.CharField(choices=[('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class'), ('General', 'General')], default='General', max_length=20)),
                ('district', models.CharField(db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag: FALSE after erasure (S-04)')),
                ('is_anonymous', models.BooleanField(default=False, help_text='True once identity is erased; outcome rows are kept')),
                ('guardian_consent', models.BooleanField(default=False, help_text='Verifiable guardian consent recorded for under-18 (DPDP s.9)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'person',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('channel', models.CharField(choices=[('WA', 'WhatsApp form'), ('SMS', 'SMS nudge'), ('IVR', 'IVR call'), ('OFFICER', 'Officer assisted call')], max_length=10)),
                ('result', models.CharField(choices=[('SENT', 'Sent'), ('NO_REPLY', 'No reply'), ('KEYWORD_REPLY', 'Keyword reply received'), ('FORM_REPLY', 'Form reply received'), ('ERROR', 'Error')], default='SENT', max_length=20)),
                ('reply_keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('reply_time', models.DateTimeField(blank=True, null=True)),
                ('reply_json', models.JSONField(blank=True, help_text='Structured reply payload', null=True)),
                ('demo_label', models.CharField(default='STUB', help_text='SANDBOX / MOCK / STUB / SIMULATED badge for this attempt', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_attempt',
                'ordering': ['followup_job_id', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('missing_provenance', models.PositiveSmallIntegerField(default=0)),
                ('inconsistent_ids', models.PositiveSmallIntegerField(default=0)),
                ('stale_demand_rows', models.PositiveSmallIntegerField(default=0)),
                ('unreached_share', models.FloatField(default=0.0, help_text='Share of due follow-ups with no reply, 0-1')),
                ('response_rate', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_quality_score',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('RETENTION_SCHEDULE', 'Retention schedule'), ('BREAK_RULE', 'Break rule'), ('SKILL_GAP_THRESHOLD', 'Skill-gap threshold'), ('FLAG_SETTINGS', 'Flag settings')], max_length=50, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'definition',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DemandSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(db_index=True, max_length=50)),
                ('occupation_code', models.CharField(db_index=True, max_length=10)),
                ('vacancy_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('NCS', 'National Career Service'), ('ASEEM', 'ASEEM'), ('MAHASWAYAM', 'Mahaswayam / CM-YKPY')], default='NCS', max_length=20)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demand_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=100)),
                ('employer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('employer_type', models.CharField(blank=True, help_text='formal | informal | self-employed | unknown', max_length=30, null=True)),
                ('wage_claimed', models.CharField(blank=True, choices=[('0-9999', 'Below ₹10,000'), ('10000-14999', '₹10,000 - 14,999'), ('15000-19999', '₹15,000 - 19,999'), ('20000-24999', '₹20,000 - 24,999'), ('25000-29999', '₹25,000 - 29,999'), ('30000-39999', '₹30,000 - 39,999'), ('40000+', '₹40,000 and above')], help_text='Wage band the trainee reported', max_length=20, null=True)),
                ('wage_verified', models.CharField(blank=True, choices=[('0-9999', 'Below ₹10,000'), ('10000-14999', '₹10,000 - 14,999'), ('15000-19999', '₹15,000 - 19,999'), ('20000-24999', '₹20,000 - 24,999'), ('25000-29999', '₹25,000 - 29,999'), ('30000-39999', '₹30,000 - 39,999'), ('40000+', '₹40,000 and above')], help_text='Wage band the employer confirmed; may differ from the claim', max_length=20, null=True)),
                ('still_employed', models.BooleanField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False, help_text='True after the employer tapped Confirm (E2)')),
                ('discrepancy_flags', models.JSONField(blank=True, default=dict, help_text='e.g. {"wage_mismatch": true, "date_mismatch": false}')),
                ('confirm_token', models.CharField(blank=True, help_text='Signed token so the employer needs no login (F-06)', max_length=64, null=True, unique=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employer',
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_date', models.DateField()),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField(blank=True, null=True)),
                ('cohort', models.CharField(blank=True, max_length=50, null=True)),
                ('certified_on', models.DateField(blank=True, help_text='Certification date; follow-up rounds are counted from here (F-04)', null=True)),
            ],
            options={
                'db_table': 'enrolment',
            },
        ),
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DOCUMENT', 'Document seen - salary slip, offer letter, stipend proof'), ('RECORD_MATCH', 'Record matched - EPFO / ESIC / DBT stipend')], max_length=20)),
                ('reviewer', models.CharField(blank=True, max_length=50, null=True)),
                ('result_verified', models.BooleanField(default=False)),
                ('level', models.CharField(blank=True, choices=[('E3', 'E3'), ('E4', 'E4')], max_length=2, null=True)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'evidence_record',
            },
        ),
        migrations.CreateModel(
            name='FollowupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField(help_text='1=T+90, 2=T+180, 3=T+270, 4=T+365 days')),
                ('due_at', models.DateTimeField()),
                ('channel_plan', models.CharField(choices=[('WA', 'WhatsApp form'), ('SMS', 'SMS nudge'), ('IVR', 'IVR call'), ('OFFICER', 'Officer assisted call')], help_text='Channel chosen at enrolment', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('REPLIED', 'Replied'), ('EXPIRED', 'Expired - escalated to an officer'), ('CANCELLED', 'Cancelled - consent withdrawn')], default='PENDING', max_length=20)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='scheduler', max_length=50)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'followup_job',
                'ordering': ['due_at', 'person_id'],
            },
        ),
        migrations.CreateModel(
            name='FollowupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(db_index=True, max_length=50)),
                ('task_type', models.CharField(choices=[('CALL', 'Call the trainee'), ('CALLBACK', 'Counsellor callback requested (S-01)'), ('EMPLOYER_CHECK', 'Ask the employer')], default='CALL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done'), ('CLOSED', 'Closed - trainee not reachable')], default='OPEN', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='1 is highest; round 4 tasks rank above round 1')),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('outcome_note', models.CharField(blank=True, default='', max_length=300)),
                ('assigned_to', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'followup_task',
                'ordering': ['priority', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('MAHASWAYAM', 'Show Mahaswayam job matches'), ('COUNSELLOR', 'Ask a counsellor to call me')], max_length=20)),
                ('job_matches_shown', models.PositiveSmallIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'help_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='IdCrosswalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('SID', 'Skill India Digital (SID)'), ('SDMS', 'SDMS'), ('CM-YKPY', 'CM-YKPY'), ('DDU-GKY', 'DDU-GKY'), ('e-Shram', 'e-Shram UAN'), ('EPFO', 'EPFO UAN')], max_length=20)),
                ('programme_id', models.CharField(max_length=50)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.CharField(default='system', max_length=50)),
            ],
            options={
                'db_table': 'id_crosswalk',
            },
        ),
        migrations.CreateModel(
            name='IdMatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_utid', models.CharField(max_length=20)),
                ('basis', models.CharField(choices=[('same_phone', 'Same phone number'), ('same_name_dob', 'Same name and date of birth'), ('same_scheme_id', 'Same external scheme ID')], max_length=30)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, default='', help_text='merged | kept_separate | pending', max_length=30)),
            ],
            options={
                'db_table': 'id_match_suggestion',
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ERASURE', 'Erasure request'), ('CORRECTION', 'Data correction'), ('CONSENT_CHANGE', 'Consent change'), ('OFFICER_LOGIN', 'Officer secondary verification')], max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('channel', models.CharField(default='SMS', help_text='SMS or EMAIL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'otp_code',
            },
        ),
        migrations.CreateModel(
            name='OutcomeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(help_text='Fixed reference date, e.g. as of today')),
                ('status', models.CharField(choices=[('wage_employment', 'Wage employment'), ('self_employment', 'Self-employment'), ('apprenticeship', 'Apprenticeship / stipend'), ('further_study', 'Further study'), ('not_working_looking', 'Not working - looking'), ('not_working_not_looking', 'Not working - not looking'), ('could_not_be_reached', 'Could not be reached')], max_length=30)),
                ('role_code', models.CharField(blank=True, help_text='NCO 2015 occupation code', max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('wage_band', models.CharField(blank=True, choices=[('0-9999', 'Below ₹10,000'), ('10000-14999', '₹10,000 - 14,999'), ('15000-19999', '₹15,000 - 19,999'), ('20000-24999', '₹20,000 - 24,999'), ('25000-29999', '₹25,000 - 29,999'), ('30000-39999', '₹30,000 - 39,999'), ('40000+', '₹40,000 and above')], max_length=20, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('evidence_level', models.CharField(choices=[('E0', 'E0 - trainee self-report'), ('E1', 'E1 - officer confirmed'), ('E2', 'E2 - employer confirmed'), ('E3', 'E3 - document seen'), ('E4', 'E4 - record matched')], default='E0', max_length=2)),
                ('reason_codes', models.JSONField(blank=True, default=dict, help_text='Grouped codes: {"training-related": ["skills_lacking"]}')),
                ('self_employment_activity', models.CharField(blank=True, choices=[('vendor', 'Street vendor'), ('freelancer', 'Freelancer'), ('micro_enterprise', 'Micro-enterprise'), ('agriculture', 'Agriculture / farm work'), ('home_based', 'Home-based work'), ('transport', 'Transport / driver'), ('other', 'Other')], max_length=30, null=True)),
                ('income_band', models.CharField(blank=True, choices=[('0-4999', 'Below ₹5,000'), ('5000-9999', '₹5,000 - 9,999'), ('10000-19999', '₹10,000 - 19,999'), ('20000-29999', '₹20,000 - 29,999'), ('30000+', '₹30,000 and above')], max_length=20, null=True)),
                ('months_active', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('establishment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stipend_band', models.CharField(blank=True, choices=[('0-9999', 'Below ₹10,000'), ('10000-14999', '₹10,000 - 14,999'), ('15000-19999', '₹15,000 - 19,999'), ('20000-24999', '₹20,000 - 24,999'), ('25000-29999', '₹25,000 - 29,999'), ('30000-39999', '₹30,000 - 39,999'), ('40000+', '₹40,000 and above')], max_length=20, null=True)),
                ('apprenticeship_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(default=1.0, help_text='Inverse-probability weight 1/p from the audit sample')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Set on erasure; the row is kept for statistics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='trainee', help_text='trainee | officer | policy | employer', max_length=50)),
            ],
            options={
                'db_table': 'outcome_event',
                'ordering': ['-reference_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('district', models.CharField(db_index=True, max_length=50)),
                ('scheme', models.CharField(default='SDMS', help_text='SDMS, SIDH, CM-YKPY or DDU-GKY', max_length=30)),
                ('is_registered', models.BooleanField(default=True, help_text='False when the centre is not on the master list')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider',
                'ordering': ['provider_id'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualification_id', models.CharField(help_text='e.g. PMKVY-Q-2023-PLUMBING', max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('occupation_code', models.CharField(db_index=True, help_text='National Classification of Occupations 2015', max_length=10)),
                ('skill_list', models.JSONField(default=list, help_text='JSON list of skills, e.g. ["bending", "welding"]')),
                ('course_duration_days', models.PositiveIntegerField(default=90)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'qualification',
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('employment-related', 'Employment-related'), ('training-related', 'Training-related'), ('personal', 'Personal')], max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('is_free_text', models.BooleanField(default=False, help_text='True when this row is uncoded free text')),
            ],
            options={
                'db_table': 'reason',
            },
        ),
        migrations.CreateModel(
            name='StatsPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('cohort_total', models.PositiveIntegerField(default=0)),
                ('reached_total', models.PositiveIntegerField(default=0)),
                ('placed_total', models.PositiveIntegerField(default=0)),
                ('placement_rate', models.FloatField(default=0.0, help_text='Placed / reached, 0-100')),
                ('response_rate', models.FloatField(default=0.0, help_text='Reached / due, 0-100')),
                ('grade_mix', models.JSONField(default=dict, help_text='{"E0": 60, "E1": 20, ...}')),
                ('weighted_rate', models.FloatField(default=0.0, help_text='Inverse-probability weighted placement rate (S-07)')),
                ('weighted_response_rate', models.FloatField(default=0.0)),
                ('sample_probability', models.FloatField(blank=True, null=True)),
                ('min_grade', models.CharField(default='E0', help_text='Grade filter this row was computed at', max_length=2)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stats_placement',
            },
        ),
        migrations.CreateModel(
            name='StatsSkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('occupation_code', models.CharField(blank=True, default='', max_length=10)),
                ('vacancy_count', models.PositiveIntegerField(default=0)),
                ('employer_skills_lacking_count', models.PositiveIntegerField(default=0)),
                ('trainee_skills_lacking_count', models.PositiveIntegerField(default=0)),
                ('signals_agree_count', models.PositiveSmallIntegerField(default=0, help_text='How many of the three signals are present')),
                ('gap_flag', models.BooleanField(default=False, help_text='True when signals_agree_count >= SKILL_GAP_THRESHOLD')),
                ('demand_snapshot_date', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stats_skill_gap',
            },
        ),
        migrations.CreateModel(
            name='StatsWageProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('wage_t3', models.CharField(blank=True, max_length=20, null=True)),
                ('wage_t6', models.CharField(blank=True, max_length=20, null=True)),
                ('wage_t12', models.CharField(blank=True, max_length=20, null=True)),
                ('retention_months', models.PositiveSmallIntegerField(default=0)),
                ('respondents', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stats_wage_progression',
            },
        ),
        migrations.CreateModel(
            name='WorkProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=60, unique=True)),
                ('employer_name', models.CharField(max_length=100)),
                ('role_code', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('still_employed', models.BooleanField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('digilocker_ref', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'db_table': 'work_proof',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contact', serialize=False, to='core.person')),
                ('own_phone', models.CharField(help_text='+91 followed by 10 digits', max_length=15)),
                ('second_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('second_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('second_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(choices=[('smartphone', 'Smartphone'), ('feature_phone', 'Feature phone'), ('shared', 'Shared phone')], default='smartphone', help_text='Declared at enrolment; drives the channel router (F-04)', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=20)),
                ('shared_phone_flag', models.BooleanField(default=False, help_text='True when the phone is shared with family members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['district'], name='person_distric_a63dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['category'], name='person_categor_fe8e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['dob'], name='person_dob_16913a_idx'),
        ),
        migrations.AddField(
            model_name='consent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_set', to='core.person'),
        ),
        migrations.AddField(
            model_name='certificatecheck',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_checks', to='core.person'),
        ),
        migrations.AddConstraint(
            model_name='demandsnapshot',
            constraint=models.UniqueConstraint(fields=('district', 'occupation_code', 'snapshot_date'), name='uniq_demand_snapshot'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolment_set', to='core.person'),
        ),
        migrations.AddField(
            model_name='followupjob',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_set', to='core.person'),
        ),
        migrations.AddField(
            model_name='contactattempt',
            name='followup_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.followupjob'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='followup_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.followupjob'),
        ),
        migrations.AddField(
            model_name='followuptask',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='core.person'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests', to='core.followuptask'),
        ),
        migrations.AddField(
            model_name='idcrosswalk',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosswalk_set', to='core.person'),
        ),
        migrations.AddField(
            model_name='idmatchsuggestion',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions', to='core.person'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='core.person'),
        ),
        migrations.AddField(
            model_name='outcomeevent',
            name='followup_job',
            field=models.ForeignKey(blank=True, help_text='Round this reply answers, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='core.followupjob'),
        ),
        migrations.AddField(
            model_name='outcomeevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_set', to='core.person'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='core.outcomeevent'),
        ),
        migrations.AddField(
            model_name='evidencerecord',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_set', to='core.outcomeevent'),
        ),
        migrations.AddField(
            model_name='employer',
            name='outcome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='core.outcomeevent'),
        ),
        migrations.AddField(
            model_name='auditsample',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_samples', to='core.outcomeevent'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='core.provider'),
        ),
        migrations.AddField(
            model_name='dataqualityscore',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_scores', to='core.provider'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='core.qualification'),
        ),
        migrations.AddField(
            model_name='reason',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_set', to='core.outcomeevent'),
        ),
        migrations.AddIndex(
            model_name='statsplacement',
            index=models.Index(fields=['district', 'course'], name='stats_place_distric_a9e062_idx'),
        ),
        migrations.AddConstraint(
            model_name='statsplacement',
            constraint=models.UniqueConstraint(fields=('course', 'provider', 'district', 'min_grade'), name='uniq_stats_placement'),
        ),
        migrations.AddIndex(
            model_name='statsskillgap',
            index=models.Index(fields=['gap_flag'], name='stats_skill_gap_fla_aff0d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='statsskillgap',
            constraint=models.UniqueConstraint(fields=('course', 'district'), name='uniq_stats_skill_gap'),
        ),
        migrations.AddConstraint(
            model_name='statswageprogression',
            constraint=models.UniqueConstraint(fields=('course', 'provider', 'district'), name='uniq_stats_wage_progression'),
        ),
        migrations.AddField(
            model_name='workproof',
            name='outcome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_proof', to='core.outcomeevent'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['own_phone'], name='contact_own_pho_fbc6da_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['device_type'], name='contact_device__d6c74d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['language'], name='contact_languag_d0f16d_idx'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['purpose'], name='consent_purpose_2a6382_idx'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['purpose', 'withdrawn_at'], name='consent_purpose_421276_idx'),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.UniqueConstraint(fields=('person', 'purpose'), name='uniq_consent_person_purpose'),
        ),
        migrations.AddIndex(
            model_name='followupjob',
            index=models.Index(fields=['status', 'due_at'], name='idx_followup_due'),
        ),
        migrations.AddIndex(
            model_name='followupjob',
            index=models.Index(fields=['person', 'round'], name='followup_jo_person__69e6f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='followupjob',
            constraint=models.UniqueConstraint(fields=('person', 'round'), name='uniq_followup_person_round'),
        ),
        migrations.AddConstraint(
            model_name='followupjob',
            constraint=models.CheckConstraint(condition=models.Q(('round__gte', 1), ('round__lte', 4)), name='chk_followup_round'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['followup_job'], name='contact_att_followu_f29336_idx'),
        ),
        migrations.AddIndex(
            model_name='contactattempt',
            index=models.Index(fields=['channel', 'result'], name='contact_att_channel_f48d85_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactattempt',
            constraint=models.UniqueConstraint(fields=('followup_job', 'attempt_number'), name='uniq_attempt_per_job'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['district', 'status'], name='followup_ta_distric_dfe9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['status', 'priority'], name='followup_ta_status_1057d1_idx'),
        ),
        migrations.AddIndex(
            model_name='idcrosswalk',
            index=models.Index(fields=['scheme'], name='id_crosswal_scheme_3bca6a_idx'),
        ),
        migrations.AddIndex(
            model_name='idcrosswalk',
            index=models.Index(fields=['scheme', 'programme_id'], name='id_crosswal_scheme_872e9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='idcrosswalk',
            constraint=models.UniqueConstraint(fields=('person', 'scheme'), name='uniq_crosswalk_person_scheme'),
        ),
        migrations.AddConstraint(
            model_name='idcrosswalk',
            constraint=models.UniqueConstraint(fields=('scheme', 'programme_id'), name='uniq_crosswalk_scheme_programme'),
        ),
        migrations.AddConstraint(
            model_name='idmatchsuggestion',
            constraint=models.UniqueConstraint(fields=('person', 'candidate_utid'), name='uniq_match_suggestion_pair'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['person', 'action'], name='otp_code_person__e1fb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomeevent',
            index=models.Index(fields=['person', 'reference_date'], name='outcome_eve_person__647449_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomeevent',
            index=models.Index(fields=['evidence_level', 'status'], name='outcome_eve_evidenc_a45712_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomeevent',
            index=models.Index(fields=['reference_date', 'status'], name='outcome_eve_referen_e5a6e9_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['kind'], name='evidence_re_kind_bd8361_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['level'], name='evidence_re_level_cae1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['verified'], name='employer_verifie_60af53_idx'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['employer_phone'], name='employer_employe_6ca5ab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsample',
            index=models.Index(fields=['sample_type'], name='audit_sampl_sample__3ba2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsample',
            index=models.Index(fields=['probability'], name='audit_sampl_probabi_7ae294_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['provider'], name='enrolment_provide_fb141c_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolment',
            index=models.Index(fields=['qualification'], name='enrolment_qualifi_2206b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.CheckConstraint(condition=models.Q(('course_end_date__isnull', True), ('course_start_date__lte', models.F('course_end_date')), _connector='OR'), name='chk_course_date_order'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.CheckConstraint(condition=models.Q(('enrolment_date__lte', models.F('course_start_date'))), name='chk_enrolment_before_course'),
        ),
        migrations.AddIndex(
            model_name='reason',
            index=models.Index(fields=['group_name', 'code'], name='reason_group_n_ae7da0_idx'),
        ),
    ]
