# Generated by Django 6.1.1 on 2026-10-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rls_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsample',
            name='sample_type',
            field=models.CharField(choices=[('NON_REPLIER', 'Non-replier sample'), ('CLAIMED_JOB', 'Claimed job sample'), ('SELF_EMPLOYMENT', 'Self-employment field-verification sample')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evidencerecord',
            name='kind',
            field=models.CharField(choices=[('DOCUMENT', 'Document seen - salary slip, offer letter, stipend proof'), ('RECORD_MATCH', 'Record matched - EPFO / ESIC / DBT stipend'), ('EMPLOYER_CONFIRM', 'Employer confirmed - one-tap link, no login (F-06)'), ('FIELD_VERIFICATION', 'Field or peer verification by an officer (F-12)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evidencerecord',
            name='level',
            field=models.CharField(blank=True, choices=[('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4')], help_text='Grade this evidence supports; E1 is written by the officer call itself, so it lives on the outcome row', max_length=2, null=True),
        ),
    ]
