# Generated by Django 6.1.1 on 2026-10-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditsample_sample_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idmatchsuggestion',
            name='basis',
            field=models.CharField(choices=[('same_phone', 'Same phone number'), ('same_name_dob', 'Same name and date of birth')], max_length=30),
        ),
    ]
